project:
  type: website
  output-dir: docs

website:
  title: "ProjectX"
  navbar:
    background: primary
    search: true
    left:
      - text: "Tutorials"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - second.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      background: light
      contents:
        - index.qmd
        - section: "Project"
          href: index.qmd
          contents:
            - href: tutorial-1.qmd
              contents:
              - basics-summary.qmd
            - introduction.qmd

    - title: "About me"
      style: "docked"
      background: light
      contents:
        - about.qmd
        - tutorials.qmd
        
    - title: "Sec"
      contents:
        - second.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



